tap "FelixKratz/formulae"
tap "borkdude/brew"

cask "nikitabobko/tap/aerospace"
cask "wezterm"

brew "borders"
brew "sketchybar"
brew "stow"
brew "asdf"
brew "neovim"
brew "eza"
brew "zoxide"
brew "fzf"
brew "postgresql"
brew "fd"
brew "babashka"
brew "gh"
brew "ical-buddy"
brew "font-jetbrains-mono-nerd-font"
